openapi: 3.0.3
info:
  title: Disputas API Contract
  version: v1.0.0
  description: Contrato mínimo del bounded context `disputas`.
servers:
  - url: https://api.aventide.gift
paths:
  /disputas/health:
    get:
      summary: Healthcheck del dominio disputas
      operationId: getDisputasHealth
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.0.0
  /disputas/commands:
    post:
      summary: Comando genérico del dominio disputas
      operationId: postDisputasCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisputasCommand'
      responses:
        '202':
          description: Comando aceptado
components:
  schemas:
    DisputasCommand:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: disputas.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
