openapi: 3.0.3
info:
  title: Disputes API
  version: v2.0.0
  description: Gestión de disputas de pagos y evidencia regulatoria.
servers:
  - url: https://api.aventide.gift
paths:
  /disputes/cases:
    post:
      summary: Crear disputa
      operationId: createDisputeCase
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateDisputeRequest' }
      responses:
        '201':
          description: Disputa creada
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DisputeResponse' }
        '404':
          description: Pago no encontrado
  /disputes/cases/{disputeId}/settle:
    post:
      summary: Resolver disputa
      operationId: settleDisputeCase
      parameters:
        - in: path
          name: disputeId
          required: true
          schema: { type: string, format: uuid }
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SettleDisputeRequest' }
      responses:
        '200':
          description: Disputa resuelta
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DisputeResponse' }
        '409':
          description: Disputa ya cerrada
components:
  parameters:
    IdempotencyKey:
      in: header
      name: Idempotency-Key
      required: true
      schema: { type: string, minLength: 16 }
  schemas:
    CreateDisputeRequest:
      type: object
      additionalProperties: false
      required: [paymentId, reasonCode, openedBy]
      properties:
        paymentId: { type: string, format: uuid }
        reasonCode: { type: string, enum: [fraud, product_not_received, duplicate_charge] }
        openedBy: { type: string, enum: [customer, issuer, internal_ops] }
    SettleDisputeRequest:
      type: object
      additionalProperties: false
      required: [decision, settledBy]
      properties:
        decision: { type: string, enum: [merchant_won, customer_won, partial_refund] }
        settledBy: { type: string, minLength: 3 }
    DisputeResponse:
      type: object
      additionalProperties: false
      required: [disputeId, paymentId, status, updatedAt]
      properties:
        disputeId: { type: string, format: uuid }
        paymentId: { type: string, format: uuid }
        status: { type: string, enum: [created, disputed, settled] }
        updatedAt: { type: string, format: date-time }
