openapi: 3.0.3
info:
  title: Estructura V2 API Contract
  version: v1.0.0
  description: Contrato mínimo del bounded context `estructura-v2`.
servers:
  - url: https://api.aventide.gift
paths:
  /estructura-v2/health:
    get:
      summary: Healthcheck del dominio estructura-v2
      operationId: getEstructuraV2Health
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.0.0
  /estructura-v2/commands:
    post:
      summary: Comando genérico del dominio estructura-v2
      operationId: postEstructuraV2Command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EstructuraV2Command'
      responses:
        '202':
          description: Comando aceptado
components:
  schemas:
    EstructuraV2Command:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: estructura-v2.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
