openapi: 3.0.3
info:
  title: Billing Docs API
  version: v2.0.0
  description: Emisión fiscal y conciliación documental de operaciones críticas.
servers:
  - url: https://api.aventide.gift
paths:
  /billing-docs/invoices:
    post:
      summary: Emitir documento fiscal
      operationId: issueInvoice
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/IssueInvoiceRequest' }
      responses:
        '201':
          description: Documento emitido
          content:
            application/json:
              schema: { $ref: '#/components/schemas/InvoiceResponse' }
        '422':
          description: Rechazo tributario
  /billing-docs/invoices/{invoiceId}/settle:
    post:
      summary: Marcar documento como liquidado
      operationId: settleInvoice
      parameters:
        - in: path
          name: invoiceId
          required: true
          schema: { type: string, format: uuid }
        - $ref: '#/components/parameters/IdempotencyKey'
      responses:
        '200':
          description: Documento liquidado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/InvoiceResponse' }
        '409':
          description: Documento ya liquidado o anulado
components:
  parameters:
    IdempotencyKey:
      in: header
      name: Idempotency-Key
      required: true
      schema: { type: string, minLength: 16 }
  schemas:
    IssueInvoiceRequest:
      type: object
      additionalProperties: false
      required: [orderId, customerTaxId, subtotal, taxAmount, total]
      properties:
        orderId: { type: string, format: uuid }
        customerTaxId: { type: string, minLength: 5 }
        subtotal: { type: integer, minimum: 1 }
        taxAmount: { type: integer, minimum: 0 }
        total: { type: integer, minimum: 1 }
    InvoiceResponse:
      type: object
      additionalProperties: false
      required: [invoiceId, fiscalNumber, status, issuedAt]
      properties:
        invoiceId: { type: string, format: uuid }
        fiscalNumber: { type: string }
        status: { type: string, enum: [created, authorized, disputed, settled] }
        issuedAt: { type: string, format: date-time }
