openapi: 3.0.3
info:
  title: Facturacion Documentos API Contract
  version: v1.0.0
  description: Contrato mínimo del bounded context `facturacion-documentos`.
servers:
  - url: https://api.aventide.gift
paths:
  /facturacion-documentos/health:
    get:
      summary: Healthcheck del dominio facturacion-documentos
      operationId: getFacturacionDocumentosHealth
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.0.0
  /facturacion-documentos/commands:
    post:
      summary: Comando genérico del dominio facturacion-documentos
      operationId: postFacturacionDocumentosCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacturacionDocumentosCommand'
      responses:
        '202':
          description: Comando aceptado
components:
  schemas:
    FacturacionDocumentosCommand:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: facturacion-documentos.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
