openapi: 3.0.3
info:
  title: Sistema De Reserva Global API Contract
  version: v1.0.0
  description: Contrato mínimo del bounded context `sistema-de-reserva-global`.
servers:
  - url: https://api.aventide.gift
paths:
  /sistema-de-reserva-global/health:
    get:
      summary: Healthcheck del dominio sistema-de-reserva-global
      operationId: getSistemaDeReservaGlobalHealth
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.0.0
  /sistema-de-reserva-global/commands:
    post:
      summary: Comando genérico del dominio sistema-de-reserva-global
      operationId: postSistemaDeReservaGlobalCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SistemaDeReservaGlobalCommand'
      responses:
        '202':
          description: Comando aceptado
components:
  schemas:
    SistemaDeReservaGlobalCommand:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: sistema-de-reserva-global.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
