openapi: 3.0.3
info:
  title: Sistema Gobernanza Multi Pais App Camaleon API Contract
  version: v1.1.0
  description: >-
    Contrato del bounded context `sistema-gobernanza-multi-pais-app-camaleon`.
    La versión v1.1 agrega endpoints explícitos de gobernanza, errores de negocio,
    idempotencia y metadatos de auditoría manteniendo compatibilidad retroactiva
    de v1.0 mediante rutas legacy marcadas como deprecated.
servers:
  - url: https://api.aventide.gift
paths:
  /governance/resolve:
    post:
      summary: Resuelve contexto de gobernanza para host, tenant y país
      operationId: postGovernanceResolve
      tags: [Governance]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GovernanceResolveRequest'
      responses:
        '200':
          description: Contexto de gobernanza resuelto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernanceResolveResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/BusinessError'
        '409':
          $ref: '#/components/responses/BusinessError'

  /governance/countries/{country_code}/ui-profile:
    get:
      summary: Obtiene el perfil de UI vigente por país
      operationId: getGovernanceCountryUiProfile
      tags: [Governance]
      parameters:
        - $ref: '#/components/parameters/CountryCodePath'
        - $ref: '#/components/parameters/TenantIdQuery'
        - $ref: '#/components/parameters/LocaleQuery'
        - $ref: '#/components/parameters/CurrencyQuery'
      responses:
        '200':
          description: Perfil de UI obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryUiProfileResponse'
        '404':
          $ref: '#/components/responses/BusinessError'
        '409':
          $ref: '#/components/responses/BusinessError'

  /governance/countries/{country_code}/rulesets/publish:
    post:
      summary: Publica ruleset de gobernanza para un país
      operationId: postGovernanceCountryRulesetPublish
      tags: [Governance]
      parameters:
        - $ref: '#/components/parameters/CountryCodePath'
        - $ref: '#/components/parameters/IdempotencyKeyHeader'
        - $ref: '#/components/parameters/CorrelationIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishRulesetRequest'
      responses:
        '202':
          description: Publicación aceptada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishRulesetAcceptedResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/BusinessError'
        '409':
          $ref: '#/components/responses/BusinessError'

  /governance/simulate-routing:
    post:
      summary: Simula resolución de routing y políticas
      operationId: postGovernanceSimulateRouting
      tags: [Governance]
      parameters:
        - $ref: '#/components/parameters/CorrelationIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulateRoutingRequest'
      responses:
        '200':
          description: Resultado de simulación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulateRoutingResponse'
        '404':
          $ref: '#/components/responses/BusinessError'
        '409':
          $ref: '#/components/responses/BusinessError'

  /sistema-gobernanza-multi-pais-app-camaleon/health:
    get:
      summary: Healthcheck del dominio sistema-gobernanza-multi-pais-app-camaleon
      operationId: getSistemaGobernanzaMultiPaisAppCamaleonHealth
      tags: [Legacy]
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.1.0

  /sistema-gobernanza-multi-pais-app-camaleon/commands:
    post:
      deprecated: true
      summary: Comando genérico legacy del dominio (deprecado desde v1.1)
      description: >-
        Endpoint conservado por compatibilidad para integraciones v1.0.
        Migrar a endpoints explícitos bajo /governance/*.
      operationId: postSistemaGobernanzaMultiPaisAppCamaleonCommand
      tags: [Legacy]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SistemaGobernanzaMultiPaisAppCamaleonCommand'
      responses:
        '202':
          description: Comando aceptado

components:
  parameters:
    CountryCodePath:
      name: country_code
      in: path
      required: true
      schema:
        type: string
        pattern: '^[A-Z]{2}$'
      description: Código ISO 3166-1 alpha-2 del país
    TenantIdQuery:
      name: tenant_id
      in: query
      required: true
      schema:
        type: string
    LocaleQuery:
      name: locale
      in: query
      required: true
      schema:
        type: string
        example: es-CO
    CurrencyQuery:
      name: currency
      in: query
      required: true
      schema:
        type: string
        pattern: '^[A-Z]{3}$'
        example: COP
    IdempotencyKeyHeader:
      name: Idempotency-Key
      in: header
      required: true
      schema:
        type: string
        minLength: 16
      description: Clave idempotente para publicación de rulesets
    CorrelationIdHeader:
      name: X-Correlation-Id
      in: header
      required: false
      schema:
        type: string
      description: Identificador de correlación para trazabilidad distribuida

  responses:
    BadRequest:
      description: Request inválido
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BusinessError:
      description: Error de negocio
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    GovernanceContext:
      type: object
      additionalProperties: false
      required:
        [host, country_code, tenant_id, locale, currency, config_version, signature_status]
      properties:
        host:
          type: string
          example: app.aventide.gift
        country_code:
          type: string
          pattern: '^[A-Z]{2}$'
        tenant_id:
          type: string
        locale:
          type: string
          example: es-MX
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
        config_version:
          type: string
          example: 2026.02.0
        signature_status:
          type: string
          enum: [verified, invalid, pending]

    GovernanceResolveRequest:
      allOf:
        - $ref: '#/components/schemas/GovernanceContext'

    GovernanceResolveResponse:
      type: object
      additionalProperties: false
      required: [context, routing_target, correlation_id]
      properties:
        context:
          $ref: '#/components/schemas/GovernanceContext'
        routing_target:
          type: string
          example: checkout-v2
        correlation_id:
          type: string

    CountryUiProfileResponse:
      type: object
      additionalProperties: false
      required: [context, ui_profile_id, ui_profile, correlation_id]
      properties:
        context:
          $ref: '#/components/schemas/GovernanceContext'
        ui_profile_id:
          type: string
        ui_profile:
          type: object
          additionalProperties: true
        correlation_id:
          type: string

    PublishRulesetRequest:
      type: object
      additionalProperties: false
      required: [context, ruleset_id, actor]
      properties:
        context:
          $ref: '#/components/schemas/GovernanceContext'
        ruleset_id:
          type: string
        ruleset_payload:
          type: object
          additionalProperties: true
        actor:
          $ref: '#/components/schemas/AuditActor'

    PublishRulesetAcceptedResponse:
      type: object
      additionalProperties: false
      required: [status, idempotency_key, correlation_id, actor]
      properties:
        status:
          type: string
          enum: [accepted]
        idempotency_key:
          type: string
        correlation_id:
          type: string
        actor:
          $ref: '#/components/schemas/AuditActor'

    SimulateRoutingRequest:
      type: object
      additionalProperties: false
      required: [context, scenario, actor]
      properties:
        context:
          $ref: '#/components/schemas/GovernanceContext'
        scenario:
          type: object
          additionalProperties: true
        actor:
          $ref: '#/components/schemas/AuditActor'

    SimulateRoutingResponse:
      type: object
      additionalProperties: false
      required: [context, decision, signature_status, correlation_id]
      properties:
        context:
          $ref: '#/components/schemas/GovernanceContext'
        decision:
          type: string
          example: allow
        signature_status:
          type: string
          enum: [verified, invalid, pending]
        correlation_id:
          type: string

    AuditActor:
      type: object
      additionalProperties: false
      required: [actor_id, actor_role]
      properties:
        actor_id:
          type: string
        actor_role:
          type: string
          example: governance-admin

    ErrorResponse:
      type: object
      additionalProperties: false
      required: [error_code, message, correlation_id]
      properties:
        error_code:
          type: string
          enum:
            - COUNTRY_NOT_ENABLED
            - HOST_NOT_MAPPED
            - INVALID_SIGNATURE
            - INCOMPATIBLE_CONFIG_VERSION
        message:
          type: string
        correlation_id:
          type: string
        details:
          type: object
          additionalProperties: true

    SistemaGobernanzaMultiPaisAppCamaleonCommand:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: sistema-gobernanza-multi-pais-app-camaleon.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
