openapi: 3.0.3
info:
  title: Sistema de Pagos API
  version: v2.0.0
  description: Operaciones money-critical para autorización, captura y liberación de pagos.
servers:
  - url: https://api.aventide.gift
paths:
  /payments/intents:
    post:
      summary: Crear intento de pago
      operationId: createPaymentIntent
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentIntentRequest'
            examples:
              card:
                value:
                  orderId: d0ec1b88-f0f7-4b6e-a8ce-e4bc1720af0d
                  amount: 129900
                  currency: COP
                  paymentMethod: card_token
                  paymentMethodRef: tok_live_8af2
      responses:
        '201':
          description: Intento creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntentResponse'
        '400': { $ref: '#/components/responses/ValidationError' }
        '409':
          description: Idempotency-Key en conflicto con payload distinto
        '422':
          description: Regla de riesgo o límites de fraude incumplidos
  /payments/intents/{paymentId}/authorize:
    post:
      summary: Autorizar pago
      operationId: authorizePayment
      parameters:
        - $ref: '#/components/parameters/PaymentId'
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizePaymentRequest'
      responses:
        '200':
          description: Pago autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404': { $ref: '#/components/responses/NotFoundError' }
        '409':
          description: Estado inválido para autorizar
  /payments/intents/{paymentId}/capture:
    post:
      summary: Capturar pago autorizado
      operationId: capturePayment
      parameters:
        - $ref: '#/components/parameters/PaymentId'
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CapturePaymentRequest'
      responses:
        '200':
          description: Pago capturado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '409':
          description: Monto de captura inválido
components:
  parameters:
    PaymentId:
      in: path
      name: paymentId
      required: true
      schema: { type: string, format: uuid }
    IdempotencyKey:
      in: header
      name: Idempotency-Key
      required: true
      schema: { type: string, minLength: 16, maxLength: 128 }
      description: Requerido para evitar dobles cargos en operaciones de escritura.
  responses:
    ValidationError:
      description: Error de validación
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    NotFoundError:
      description: Recurso no encontrado
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
  schemas:
    CreatePaymentIntentRequest:
      type: object
      additionalProperties: false
      required: [orderId, amount, currency, paymentMethod, paymentMethodRef]
      properties:
        orderId: { type: string, format: uuid }
        amount: { type: integer, minimum: 1 }
        currency: { type: string, enum: [COP, USD, EUR] }
        paymentMethod: { type: string, enum: [card_token, pse, wallet] }
        paymentMethodRef: { type: string, minLength: 3 }
    AuthorizePaymentRequest:
      type: object
      additionalProperties: false
      required: [authorizedBy, riskScore]
      properties:
        authorizedBy: { type: string, enum: [issuer, acquirer, internal_risk] }
        riskScore: { type: integer, minimum: 0, maximum: 1000 }
    CapturePaymentRequest:
      type: object
      additionalProperties: false
      required: [captureAmount]
      properties:
        captureAmount: { type: integer, minimum: 1 }
    PaymentIntentResponse:
      allOf:
        - $ref: '#/components/schemas/PaymentResponse'
        - type: object
          properties:
            status: { type: string, enum: [created] }
    PaymentResponse:
      type: object
      additionalProperties: false
      required: [paymentId, orderId, amount, currency, status, processedAt]
      properties:
        paymentId: { type: string, format: uuid }
        orderId: { type: string, format: uuid }
        amount: { type: integer }
        currency: { type: string }
        status: { type: string, enum: [created, authorized, captured, released] }
        processedAt: { type: string, format: date-time }
    ErrorResponse:
      type: object
      additionalProperties: false
      required: [code, message]
      properties:
        code: { type: string, example: PAYMENT_INVALID_STATE }
        message: { type: string }
