openapi: 3.0.3
info:
  title: Reservas Global API
  version: v2.0.0
  description: Bloqueo y liberación de inventario global para evitar sobreventa.
servers:
  - url: https://api.aventide.gift
paths:
  /reservas-global/holds:
    post:
      summary: Crear hold global de inventario
      operationId: createGlobalReservationHold
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateReservationHoldRequest' }
      responses:
        '201':
          description: Hold creado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ReservationHoldResponse' }
        '409':
          description: Inventario no disponible
  /reservas-global/holds/{holdId}/release:
    post:
      summary: Liberar hold global
      operationId: releaseGlobalReservationHold
      parameters:
        - in: path
          name: holdId
          required: true
          schema: { type: string, format: uuid }
        - $ref: '#/components/parameters/IdempotencyKey'
      responses:
        '200':
          description: Hold liberado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ReservationHoldResponse' }
components:
  parameters:
    IdempotencyKey:
      in: header
      name: Idempotency-Key
      required: true
      schema: { type: string, minLength: 16 }
  schemas:
    CreateReservationHoldRequest:
      type: object
      additionalProperties: false
      required: [sku, quantity, expiresAt, channel]
      properties:
        sku: { type: string }
        quantity: { type: integer, minimum: 1 }
        expiresAt: { type: string, format: date-time }
        channel: { type: string, enum: [web, app, partner_api] }
    ReservationHoldResponse:
      type: object
      additionalProperties: false
      required: [holdId, sku, quantity, status]
      properties:
        holdId: { type: string, format: uuid }
        sku: { type: string }
        quantity: { type: integer }
        status: { type: string, enum: [created, authorized, released, settled] }
