openapi: 3.0.3
info:
  title: Sistema De Moderacion API Contract
  version: v1.0.0
  description: Contrato mínimo del bounded context `sistema-de-moderacion`.
servers:
  - url: https://api.aventide.gift
paths:
  /sistema-de-moderacion/health:
    get:
      summary: Healthcheck del dominio sistema-de-moderacion
      operationId: getSistemaDeModeracionHealth
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.0.0
  /sistema-de-moderacion/commands:
    post:
      summary: Comando genérico del dominio sistema-de-moderacion
      operationId: postSistemaDeModeracionCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SistemaDeModeracionCommand'
      responses:
        '202':
          description: Comando aceptado
components:
  schemas:
    SistemaDeModeracionCommand:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: sistema-de-moderacion.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
