openapi: 3.0.3
info:
  title: Waterfall Engine API
  version: v2.0.0
  description: Orquestación de distribución de fondos por prioridad de reglas.
servers:
  - url: https://api.aventide.gift
paths:
  /waterfall/allocations:
    post:
      summary: Ejecutar waterfall de asignación
      operationId: createWaterfallAllocation
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/WaterfallAllocationRequest' }
      responses:
        '201':
          description: Asignación creada
          content:
            application/json:
              schema: { $ref: '#/components/schemas/WaterfallAllocationResponse' }
        '422':
          description: Regla de cascade inválida
  /waterfall/allocations/{allocationId}/release:
    post:
      summary: Liberar fondos retenidos
      operationId: releaseWaterfallAllocation
      parameters:
        - in: path
          name: allocationId
          required: true
          schema: { type: string, format: uuid }
        - $ref: '#/components/parameters/IdempotencyKey'
      responses:
        '200':
          description: Fondos liberados
          content:
            application/json:
              schema: { $ref: '#/components/schemas/WaterfallAllocationResponse' }
        '409':
          description: Estado no liberable
components:
  parameters:
    IdempotencyKey:
      in: header
      name: Idempotency-Key
      required: true
      schema: { type: string, minLength: 16 }
  schemas:
    WaterfallAllocationRequest:
      type: object
      additionalProperties: false
      required: [settlementId, grossAmount, currency, legs]
      properties:
        settlementId: { type: string, format: uuid }
        grossAmount: { type: integer, minimum: 1 }
        currency: { type: string, enum: [COP, USD] }
        legs:
          type: array
          minItems: 1
          items:
            type: object
            additionalProperties: false
            required: [beneficiaryId, priority, percentage]
            properties:
              beneficiaryId: { type: string, format: uuid }
              priority: { type: integer, minimum: 1 }
              percentage: { type: number, minimum: 0, maximum: 100 }
    WaterfallAllocationResponse:
      type: object
      additionalProperties: false
      required: [allocationId, status, releasedAmount]
      properties:
        allocationId: { type: string, format: uuid }
        status: { type: string, enum: [created, authorized, released, settled] }
        releasedAmount: { type: integer, minimum: 0 }
