openapi: 3.0.3
info:
  title: Waterfall Engine V10 API Contract
  version: v1.0.0
  description: Contrato mínimo del bounded context `waterfall-engine-v10`.
servers:
  - url: https://api.aventide.gift
paths:
  /waterfall-engine-v10/health:
    get:
      summary: Healthcheck del dominio waterfall-engine-v10
      operationId: getWaterfallEngineV10Health
      responses:
        '200':
          description: Dominio operativo
          content:
            application/json:
              schema:
                type: object
                required: [status, version]
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                    example: v1.0.0
  /waterfall-engine-v10/commands:
    post:
      summary: Comando genérico del dominio waterfall-engine-v10
      operationId: postWaterfallEngineV10Command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaterfallEngineV10Command'
      responses:
        '202':
          description: Comando aceptado
components:
  schemas:
    WaterfallEngineV10Command:
      type: object
      additionalProperties: false
      required: [id, type, timestamp]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: waterfall-engine-v10.execute
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
